# Site settings
title: DATA PRIBADI
header-img: img/home-bg.jpg
email:dewiardianti724@gmail.com
copyright_name: DATA PRIBADI
description: "Selamat membaca. semoga dapat nilai bagus!"
baseurl: "/dewiardianti.github.io"
url: "http://dewiardianti724@gmail.com"
twitter_username: -
github_username:  dewiardianti1@github.io
facebook_username:  Dewi Ardianti Kadir
email_username:  dewiardianti724@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
